site_name: Blacad Docs
site_url: https://Blacad.github.io/blog/
repo_name: Blacad/blog
repo_url: https://github.com/Blacad/blog/
edit_uri: tree/main/docs
theme: 
  name: 'material'
  language: 'zh'
  features:
    - content.code.annotate
    - navigation.tracking
    - navigation.top
    - navigation.tabs
    - navigation.footer
    - navigation.indexes
    - header.autohide
  custom_dir: overrides
  favicon: images/favicon.png
  palette:
    - scheme: slate
markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
plugins:
  - search
# mkdocs.yml 相关配置
markdown_extensions:
  - abbr
  # 高亮
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # 数学公式支持
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.inlinehilite
extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - https://unpkg.com/mermaid/dist/mermaid.css
nav:
  - 首页: 
    - index.md
  - CS:
    - CS61A:
      - CS/CS61A/index.md
      - CS/CS61A/L1 Welcome.md
      - CS/CS61A/L2 Functions.md
      - CS/CS61A/L3 Control.md
      - CS/CS61A/L4 Higher-Order Function.md
      - CS/CS61A/L5 Environments.md
      - CS/CS61A/L6 Sounds.md
      - CS/CS61A/L7 Function Abstract.md
      - CS/CS61A/L8 Function Example.md
      - CS/CS61A/L9 Recursion.md
      - CS/CS61A/L10 Tree Recursion.md
      - CS/CS61A/L11 Sequences.md
      - CS/CS61A/L12 Containers.md
      - CS/CS61A/L13 Data Abstraction.md
      - CS/CS61A/L14 Trees.md
      - CS/CS61A/L15 Mutability.md
      - CS/CS61A/L16 Iterators.md
      - CS/CS61A/L17 Generators.md
      - CS/CS61A/L18 Objects.md
      - CS/CS61A/L19 Class Attributes.md
      - CS/CS61A/L20 Inheritance.md
      - CS/CS61A/L21 Representations.md
      - CS/CS61A/L22 Composition.md
      - CS/CS61A/L23 Efficiency.md
      - CS/CS61A/L24 Decomposition.md
      - CS/CS61A/L25 Data Example.md
      - CS/CS61A/L28 Scheme.md
      - CS/CS61A/L29 Scheme Lists.md
      - CS/CS61A/L30 Calculator.md
      - CS/CS61A/L31 Interpreters.md
      - CS/CS61A/L32 Tail Calls.md
      - CS/CS61A/L33 Programs as Data.md
      - CS/CS61A/L34 Macros.md
      - CS/CS61A/L35 SQL.md
      - CS/CS61A/L36 Tables.md
      - CS/CS61A/L37 Aggregation.md
      - CS/CS61A/L38 Database.md
      - CS/CS61A/L39 思考解决问题.md
      - CS/CS61A/Hog/Hog.md
      - CS/CS61A/Cats/Cats.md
      - CS/CS61A/Ants/Ants.md
      - CS/CS61A/Scheme/Scheme.md
      - CS/CS61A/Note.md
    - CS70:
      - CS/CS70/index.md
      - CS/CS70/Note10 Counting.md
      - CS/CS70/Note11 Countability.md
      - CS/CS70/Note12 Computability.md
      - CS/CS70/Note13 Discrete Probability.md
      - CS/CS70/Note14 Conditional Probability.md
      - CS/CS70/Note15 RV.md
      - CS/CS70/Note16 RV.md
      - CS/CS70/Note17 Concentration Inequalities and the Laws of Large Numbers.md
      - CS/CS70/Note18 Hashing and Load Balance.md
      - CS/CS70/Note19 Geometric and Poisson Distributions.md
      - CS/CS70/Note20 Continuous Probability Distribution.md
      - CS/CS70/Note21 Markov Chains.md
      - CS/CS70/不完备补充.md
      - CS/CS70/限与界.md
  # - 城市: 
  #   - 城市/index.md
  #   - 华北:
  #     - 北京: 城市/华北/北京.md
  #   - 城市/杭州.md
  #   - 城市/武汉.md
  # - 马克思主义:
  #   - 马克思主义/index.md
  #   - 哲学: 
  #     - 马克思主义/马克思主义哲学/index.md
  #     - 马克思主义/马克思主义哲学/辩证唯物论.md
  #     - 马克思主义/马克思主义哲学/唯物辩证法.md